appName : Features App
theme : org.wso2.uuf.sample.theme.default
menu :
  main :
    Home : {link: "", icon: "fw-home"}
    Features :
      Call a OSGi: {link: "call-osgi", icon: "fw fw-service"}
      Call a OSGi Service: {link: "call-osgi-service", icon: "fw fw-service"}
      Include a Module: {link: "include-module", icon: "fw fw-use"}
#      Http Form POST : {link: "http-form"} #TODO un-comment after implementing POST handling
      Send HTTP Error : {link: "send-error", icon: "fw fw-bug"}
      Send HTTP Redirect : {link: "send-redirect"}
      Session : {link: "session", icon: "fw fw-user"}
      Theme :
        this : {link: "theme"}
        Session Scope : {link: "theme/session-scope"}
      Menu : {link: "menu", icon: "fw fw-list"}
errorPages:
  "404": /base/error/404
  default: /base/error/default