appName : Pet Store
elementsPerPage: 10
theme : org.wso2.uuf.theme.default
menu :
  main :
    Home : { icon: "fw-home", link: "#home"}
    Pets :
      See all our amazing pets : { icon: "fw fw-list", link: "pets"}
      Add a new pets : { icon: "fw fw-add", link: "pets/new" }
      Pet of the month : { icon: "fw fw-bug", link: "pets/snowball" }
errorPages:
 "404": /base/error/404
 default: /base/error/default