appName : Features App
elementsPerPage: 10
theme : org.wso2.uuf.theme.default
menu :
  main :
    Home : { icon: "fw-home", link: "#home" }
    Features :
      Call a OSGi Service:  { icon: "fw fw-list", link: "call-osgi" }
      Http Form POST : { icon: "fw fw-add", link: "http-form" }
      Send HTTP Error : { icon: "fw fw-bug", link: "send-error" }
      Send HTTP Redirect : { icon: "fw fw-bug", link: "send-redirect" }
      Session : { icon: "fw fw-bug", link: "session" }
      Theme : { icon: "fw fw-bug", link: "theme" }
      Menu : { icon: "fw fw-bug", link: "menu" }